port=80
readiness_path="/"
from_to_www_redirect=true
emoji="🧪"

[build_secrets]
"my-secret" = { encrypted = "TeCfUZ8f_QGd4nl5QCN3Ol_N1xUOPJVKZ92hffWLTUUvoPVAhHPVDVuV5JjCD6SgI3P-5zLNduu2o_NpYWs6FAARf86dfutSqSc0a-2Fa3dVUeI-zxV78eOJEky6mmt_m9m-pfGstrAhw7ri8cI3-NHKrFs2jQG5nJbhXFogXfZkipw6" }
