port=80
readiness_path="/"
from_to_www_redirect=true
emoji="🧪"
[build]
build_in_kubernetes = true

[build_secrets.my-secret]
"test.txt" = { encrypted = "jecPORaHAPlzpwJANPpFYdxgIi7IBLtK0uajXJyczg_k4n99-IKUwoLMN7Ht43_x_50z6LFANoDA3l4nvz81C5U6_HEe4TBSEx0_SKAJyl37f_dzXhwtJ4C_8_o8Rkm59y-GG2QrR9N7aQGntXpbB0hNKrj6YchUhsWwpPWH4jGtLw" }
