port=80
readiness_path="/"
#auto_deploy_env="prod"

[env.common]
YOUR_ENVIRONMENT_VARIABLE = { encrypted = "YAB0Kr10UF0KMVg9evejiuvcoPn8X2lzVsSGv6yyTjn3B1af-X_mWXqa38nio6Mug-UOXnN7TrBhD-kBOOJQurKBg3-kGNh9KhyKewJ-i6W95qD3I1npN2bYz3zI7VubVz7TVhXOa9KO61YHLU1J2mbl" }

[build]
build_in_kubernetes = true
