port=80
readiness_path="/"
#auto_deploy_env="prod"

[env.common]
YOUR_ENVIRONMENT_VARIABLE = { encrypted = "yUwudnldnO0YHP79-Xx091g3ITYVdNIZPa-guBkczRFG4wq3DSPJJ1KQvbDk_kR0RyPN6GsqBViv0N3Q4EgHqzD8Zw3C1qhfPj6ypDvcNKJiFUZ_Q-EM9o_OxoBm2rMrm9PLbC5k64lOhNFaVWcy3P9ZSp-FLydgHMXAlTdaOQ" }

[build]
build_in_kubernetes = true
