port=80
readiness_path="/"
#auto_deploy_env="prod"

[env.common]
# Hei verden. Dette er en secret
YOUR_ENVIRONMENT_VARIABLE = { encrypted = "iakECGLclUb8sOoaFmRCifqMWRm1jV7OU82YQEcnshFr8lyQeLpjqgr9-w981DLYYt5U7F5NUAOdZbcdp8uMnbhRJTrrEreZqjQBuMWmEkmF66HiT0QnFh9jkGCGejpf9d2x3IFt9HiI63pJQ_x_x75l0A" }

[build]
build_in_kubernetes = true
